-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.credit_history
(
    id smallint NOT NULL,
    credit_history smallint NOT NULL,
    CONSTRAINT credit_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dependents
(
    id smallint NOT NULL,
    dependents character varying(2) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dependents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.education
(
    id smallint NOT NULL,
    education character varying(12) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT education_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.gender
(
    id smallint NOT NULL,
    gender character varying(6) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT gender_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.married
(
    id smallint NOT NULL,
    married character varying(3) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT married_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.property_area
(
    id smallint NOT NULL,
    property_area character varying(9) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT property_area_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.self_employed
(
    id smallint NOT NULL,
    self_employed character varying(3) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT self_employed_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.test
(
    id smallint NOT NULL,
    "Loan_ID" character varying(8) COLLATE pg_catalog."default",
    "Gender" smallint,
    "Married" smallint,
    "Dependents" smallint,
    "Education" smallint,
    "Self_Employed" smallint,
    "ApplicantIncome" integer,
    "CoapplicantIncome" integer,
    "LoanAmount" integer,
    "Loan_Amount_Term" integer,
    "Credit_History" smallint,
    "Property_Area" smallint,
    CONSTRAINT test_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.train
(
    id smallint NOT NULL,
    "Loan_ID" character varying(8) COLLATE pg_catalog."default",
    "Gender" smallint,
    "Married" smallint,
    "Dependents" smallint,
    "Education" smallint,
    "Self_Employed" smallint,
    "ApplicantIncome" integer,
    "CoapplicantIncome" integer,
    "LoanAmount" integer,
    "Loan_Amount_Term" integer,
    "Credit_History" smallint,
    "Property_Area" smallint,
    "Loan_Status" character varying(1) COLLATE pg_catalog."default",
    CONSTRAINT train_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.test
    ADD FOREIGN KEY ("Gender")
    REFERENCES public.gender (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.test
    ADD FOREIGN KEY ("Married")
    REFERENCES public.married (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.test
    ADD FOREIGN KEY ("Dependents")
    REFERENCES public.dependents (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.test
    ADD FOREIGN KEY ("Education")
    REFERENCES public.education (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.test
    ADD FOREIGN KEY ("Self_Employed")
    REFERENCES public.self_employed (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.test
    ADD FOREIGN KEY ("Credit_History")
    REFERENCES public.credit_history (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.test
    ADD FOREIGN KEY ("Property_Area")
    REFERENCES public.property_area (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.train
    ADD FOREIGN KEY ("Gender")
    REFERENCES public.gender (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.train
    ADD FOREIGN KEY ("Married")
    REFERENCES public.married (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.train
    ADD FOREIGN KEY ("Dependents")
    REFERENCES public.dependents (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.train
    ADD FOREIGN KEY ("Education")
    REFERENCES public.education (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.train
    ADD FOREIGN KEY ("Self_Employed")
    REFERENCES public.self_employed (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.train
    ADD FOREIGN KEY ("Credit_History")
    REFERENCES public.credit_history (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.train
    ADD FOREIGN KEY ("Property_Area")
    REFERENCES public.property_area (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;